### ISSUE TITLE
ToDo: Create file structure

### ISSUE THREAD

**Issue by mnaray** [Mustard4868/blurple-lightsaber#4]
# Description
Plan and create file structure for docker stack

# Steps/Progress
- [x] Plan directories for each service
- [x] Plan data storage
- [x] Plan docker-compose-file (roughly)
