### ISSUE TITLE
ToDo: Initialize projects for services

### ISSUE THREAD

**Issue by mnaray** [Mustard4868/blurple-lightsaber#5]
# Description
Generate projects and install dependencies

# Steps/Progress
- [ ] Init Express project
- [ ] Add Express deps
- [ ] Init React project
- [ ] Add React deps
- [ ] Init (and set up) DB
