### ISSUE TITLE
ToDo: Configure docker stuff

### ISSUE THREAD

**Issue by mnaray** [Mustard4868/blurple-lightsaber#6]
# Description
Write docker-compose file and dockerfile

# Steps/Progress
- [ ] Write Dockerfile for Frontend
- [ ] Write Dockerfile for Backend
- [ ] Write docker-compose file
- [ ] Test by running a simulatneous compose build
